services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PG_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      PG_USER: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
